- concordium-sdk/src/main/java/com/concordium/sdk/responses/blocksummary/MicroGTUPerEuro.java
Fix deserialization error related to MicroGTUPerEuro.java in particular the types for the fields `denominator` and `numerator` were wrong. 
Fixed the types such that it can deserialize uint64 values. 
> Fixed deserialization error.

- CHANGELOG.md
- concordium-sdk/pom.xml
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/AccountAddress.java
- concordium-sdk/src/test/java/com/concordium/sdk/transactions/AccountAddressTest.java
Aims to fix #15 
Expanded the AccountAddress type with the following two methods: 
`AccountAddress newAlias(int alias)`
Creates a new alias from an `AccountAddress`
`boolean isAliasOf(AccountAddress other)`
Checks whether an `AccountAddress` is an alias of the other.
There is now also a CHANGELOG.md in the root of the repository which should be used for the future.
> Support for account alias

- CHANGELOG.md
- README.md
- concordium-sdk/src/main/java/com/concordium/sdk/BlocksAtHeightRequest.java
- concordium-sdk/src/main/java/com/concordium/sdk/Client.java
- concordium-sdk/src/main/java/com/concordium/sdk/exceptions/BlockNotFoundException.java
- concordium-sdk/src/main/java/com/concordium/sdk/responses/BlocksAtHeight.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/AccountAddress.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/Base58.java
Support for GetBlocksAtHeight
The Client API now exposes 
`BlocksAtHeight getBlocksAtHeight(long height) throws BlockNotFoundException`
If one or more blocks was found at the given height then it returns a list of block hashes. 
If no blocks were found the a `BlockNotFoundException` is thrown.
> Support for GetBlocksAtHeight

- CHANGELOG.md
- README.md
- concordium-sdk/pom.xml
- concordium-sdk/src/main/java/com/concordium/sdk/Client.java
- concordium-sdk/src/main/java/com/concordium/sdk/responses/blockinfo/BlockInfo.java
- concordium-sdk/src/main/java/com/concordium/sdk/serializing/JsonMapper.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/AccountAddress.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/AccountTransaction.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/BlockItem.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/BlockItemType.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/GTUAmount.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/Index.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/Memo.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/Payload.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/TransactionHeader.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/TransactionSignature.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/Transfer.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/TransferWithMemo.java
- concordium-sdk/src/main/java/com/concordium/sdk/types/UInt16.java
- concordium-sdk/src/main/java/com/concordium/sdk/types/UInt32.java
- concordium-sdk/src/main/java/com/concordium/sdk/types/UInt64.java
- concordium-sdk/src/test/java/com/concordium/sdk/transactions/TransferTest.java
- concordium-sdk/src/test/java/com/concordium/sdk/transactions/TransferWithMemoTest.java
Add inverses to various `getBytes` methods.
In addition to deserialization methods, ensure consistent order of key serialization by using an order based map.
> Add methods for deserializing transactions and block items. And another endpoint.

- CHANGELOG.md
- concordium-sdk/pom.xml
Release 1.4.0
Fix a parsing bug for `AccountInfo` and made some types public.
- Fix parsing bug for `AccountInfo` where scheduled releases was not included.
- Transaction `Status` is now public.
- `BlockItem` is now public.
> Release 1.4.0

- CHANGELOG.md
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/AccountTransaction.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/Payload.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/Transfer.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/TransferTransaction.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/TransferWithMemo.java
When deconstructing a `BlockItem` it is useful to know the type of the underlying `Payload` in advance.
Exposed `Payload.PayloadType getType` for `AccountTransaction`.
> AccountTransaction now exposes `getType` for the payload.

- CHANGELOG.md
- concordium-sdk/pom.xml
Release 1.6.0
- `AccountTransaction` now exposes a `getType` function which
returns the type of the underlying `Payload`.
Extended `AcccountTransaction` with a `getType` method. 
> Release 1.6.0

- CHANGELOG.md
- concordium-sdk/src/main/java/com/concordium/sdk/Client.java
- concordium-sdk/src/main/java/com/concordium/sdk/Connection.java
Fix  a bug which caused the `Client` to have a _global_ absolute timeout from when it was initialized. 
The client now correctly sets a timeout for each request. 
> Fix bug where timeout was not correctly set for the `Client`.

- CHANGELOG.md
- README.md
- concordium-sdk/src/main/java/com/concordium/sdk/Connection.java
- concordium-sdk/src/main/java/com/concordium/sdk/Credentials.java
- concordium-sdk/src/main/java/com/concordium/sdk/Header.java
- concordium-sdk/src/main/java/com/concordium/sdk/responses/transactionstatus/TransactionContents.java
- concordium-sdk/src/main/java/com/concordium/sdk/responses/transactionstatus/UpdateType.java
Provide the user with the option of providing additional http headers for the grpc connection.
Introduced a `Header` type  and a new `Credentials.builder()` which supports the option of providing more http headers. 
Example usage: 
```
Credentials.builder()
.authenticationToken("rpcadmin")
.withAdditionalHeader(Header.from("foo", "bar"))
.withAdditionalHeader(Header.from("baz", "qux"))
.build()
```
> Added the possibillity for providing custom http headers for the grpc connection.

- CHANGELOG.md
- concordium-sdk/pom.xml
Release 1.7.0
- Allow consumers to provide extra HTTP headers for the gRPC connection.
Updated the `pom.xml` and `CHANGELOG.md` with the new changes.
> Release 1.7.0

- CHANGELOG.md
- README.md
- concordium-sdk/src/main/java/com/concordium/sdk/Client.java
- concordium-sdk/src/main/java/com/concordium/sdk/Connection.java
- concordium-sdk/src/main/java/com/concordium/sdk/TLSConfig.java
- concordium-sdk/src/main/java/com/concordium/sdk/exceptions/ClientInitializationException.java
Support for configuring TLS, mTLS etc.
Introduced a `TLSConfig` type which can be used together with `Connection` for configuring TLS. 
Variants supported:
- 'auto' - will use the default jvm trust store. 
- 'custom' - TLS where the servers certificate or a CA authorizing it can be provided. 
- 'mTLS' - mutual TLS where the client is also provided with a certificate and a private key.
> Support for configuring TLS.

- concordium-sdk/pom.xml
Fix a compilation error when using the @Singular annotation provided by Lombok and maven 3.8.1. 
Update the lombok dependency from 1.18.20 to 1.18.24
> Upgrade lombok to 1.18.24

- CHANGELOG.md
- concordium-sdk/pom.xml
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/AccountAddress.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/CredentialRegistrationId.java
- concordium-sdk/src/test/java/com/concordium/sdk/transactions/AccountAddressTest.java
Support for creating an `AccountAddress` from the credential registration id. 
- new type `CredentialRegistrationId`
- AccountAddress.from(CredentialRegistrationID) added
> Support for creating account address from regid

- CHANGELOG.md
- README.md
- concordium-sdk/pom.xml
- concordium-sdk/src/main/java/com/concordium/sdk/Client.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/BlockItem.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/RawTransaction.java
- concordium-sdk/src/test/java/com/concordium/sdk/transactions/RawTransactionTest.java
- concordium-sdk/src/test/java/com/concordium/sdk/transactions/TransactionTestHelper.java
- concordium-sdk/src/test/java/com/concordium/sdk/transactions/TransferTransactionTest.java
Solves https://github.com/Concordium/concordium-java-sdk/issues/55
Introduced a new type `RawTransaction` which can be constructed from a `byte[]` via `RawTransaction.from(byte[] rawBytes)`.
> Support for submitting raw transactions.

- CHANGELOG.md
- concordium-sdk/src/main/java/com/concordium/sdk/Client.java
- concordium-sdk/src/main/java/com/concordium/sdk/responses/cryptographicparameters/CryptographicParameters.java
- concordium-sdk/src/main/java/com/concordium/sdk/responses/cryptographicparameters/Value.java
Solves https://github.com/Concordium/concordium-java-sdk/issues/63
Introduced a new type `CryptographicParameters` which can be obtained via 
`Client#getCryptographicParameters`
> Support for `getCryptographicParameters`

- CHANGELOG.md
- concordium-sdk/src/main/java/com/concordium/sdk/responses/blocksummary/updates/queues/EnqueuedUpdate.java
- concordium-sdk/src/main/java/com/concordium/sdk/responses/transactionstatus/UpdateEnqueuedResult.java
`UpdateEnqueuedResult` parsed the `effectiveTime` wrongly. It interpreted the timestamp in milliseconds instead of seconds.
Fix the bug by now parsing `effectiveTime` in seconds. 
> UpdateEnqueuedResult now parses `effectiveTime` in seconds.

- CHANGELOG.md
- concordium-sdk/pom.xml
Release 4.0.0 of the Concordium java sdk. 
See CHANGELOG for details. 
But in particular this supports the upcoming protocol 5 on the concordium network. 
> Release 4.0.0

- concordium-sdk/pom.xml
Fix mac M1/M2 chip build. 
Two issues were identified in mac M1/M2 chip build:
- Issue with build version of protocArtifact and pluginArtifact properties.
- Java 1.8 incompatibility with M1 chip. Java 1.8 is not officially supported on the Apple M1 chip architecture. However, it is possible to install and use Java 1.8 on an M1-based Mac by using Rosetta 2, which is a built-in translation layer that allows apps designed for x86_64 architecture to run on Apple Silicon.
There are two profiles defined: mac-os and other-os. The mac-os profile is activated when the operating system is Mac, and it sets the protocArtifact and pluginArtifact properties to constant values. The other-os profile is activated when the operating system is not Mac, and it uses the ${os.detected.classifier} variable in …
> DRAFT: Fix mac M1/M2 chip build

- CHANGELOG.md
- concordium-sdk/pom.xml
Release 4.2.0 
- Added initial support for GRPC V2
- Added initial support for GRPC V2 query GetAnonymityRevokers
- Added CLI example for GRPC V2 query GetAnonymityRevokers
- Added support for GRPC V2 GetBlocks
- Added support for GRPC V2 GetFinalizedBlocks
- Added support for M1/M2 Mac.
Updated the  CHANGELOG.md and version to 4.2.0.
> Release 4.2.0

- concordium-sdk/src/main/java/com/concordium/sdk/responses/ProtocolVersion.java
Add the v6 to the ProtocolVersion enum.
Note that this does not directly give support for P6 (this is done here https://github.com/Concordium/concordium-java-sdk/pull/250) - hence the changelog will be updated as part of the pr mentioned.
But this serves the purpose of preventing that the v1 client cannot parse existing endpoints on P6.
> P6 variant in the ProtocolVersion

- concordium-sdk-examples/src/main/java/com/concordium/sdk/examples/GetBlockTransactionEvents.java
- concordium-sdk-examples/src/main/java/com/concordium/sdk/examples/InstanceStateLookup.java
Adding an example using `getBlockTransactionEvents`.
> Add example for GetBlockTransactionEvents

- CHANGELOG.md
- concordium-sdk-examples/src/main/java/com/concordium/sdk/examples/GetBlockCertificates.java
- concordium-sdk/src/main/java/com/concordium/sdk/ClientV2.java
- concordium-sdk/src/main/java/com/concordium/sdk/crypto/BLSSignature.java
- concordium-sdk/src/main/java/com/concordium/sdk/responses/Epoch.java
- concordium-sdk/src/main/java/com/concordium/sdk/responses/Round.java
- concordium-sdk/src/main/java/com/concordium/sdk/responses/blockcertificates/BlockCertificates.java
- concordium-sdk/src/main/java/com/concordium/sdk/responses/blockcertificates/EpochFinalizationEntry.java
- concordium-sdk/src/main/java/com/concordium/sdk/responses/blockcertificates/FinalizerRound.java
- concordium-sdk/src/main/java/com/concordium/sdk/responses/blockcertificates/QuorumCertificate.java
- concordium-sdk/src/main/java/com/concordium/sdk/responses/blockcertificates/QuorumSignature.java
- concordium-sdk/src/main/java/com/concordium/sdk/responses/blockcertificates/SuccessorProof.java
- concordium-sdk/src/main/java/com/concordium/sdk/responses/blockcertificates/TimeoutCertificate.java
- concordium-sdk/src/main/java/com/concordium/sdk/responses/blockcertificates/TimeoutSignature.java
- concordium-sdk/src/test/java/com/concordium/sdk/ClientV2GetBlockCertificatesTest.java
Support the new `GetBlockCertificates` query.
Added classes: `BlockCertificates`, `EpochFinalizationEntry`, `FinalizerRound`, `QuorumCertificate`, `QuorumSignature`, `SuccessorProof`, `TimeoutCertificate` and `TimeoutSignature`.
Added tests and an example of the implemented method.
> Get block certificates

- .github/workflows/release.yml
- concordium-sdk/.gitignore
- concordium-sdk/pom.xml
- release/README.md
Adds a workflow automatically compiling native dependencies and attaching a jar with the dependencies embedded to new releases when created. Also generates javadoc both as a .jar attached to the release and as a "site" deployed to https://concordium.github.io/concordium-java-sdk/javadoc/concordium-sdk/apidocs/
Result of release demonstrated as release in https://github.com/magnusbechwind/concordium-java-sdk/releases/tag/v.5.1.2
Added workflow and updated the pom
In addition to the proposed changes, the settings/pages should be changed to the following to enable deplayment of javadoc 
> Release workflow 

- CHANGELOG.md
- concordium-sdk-examples/src/main/java/com/concordium/sdk/examples/GetBakerEarliestWinTime.java
- concordium-sdk-examples/src/main/java/com/concordium/sdk/examples/GetFirstBlockEpoch.java
- concordium-sdk-examples/src/main/java/com/concordium/sdk/examples/GetWinningBakersEpoch.java
- concordium-sdk/src/main/java/com/concordium/sdk/ClientV2.java
- concordium-sdk/src/main/java/com/concordium/sdk/ClientV2MapperExtensions.java
- concordium-sdk/src/main/java/com/concordium/sdk/requests/EpochQuery.java
- concordium-sdk/src/main/java/com/concordium/sdk/responses/winningbaker/WinningBaker.java
- concordium-sdk/src/test/java/com/concordium/sdk/ClientV2GetWinningBakersEpochTest.java
- crypto-jni/Cargo.lock
Support the new queries `GetWinningBakersEpoch`, `GetFirstBlockEpoch` and  `GetBakerEarliestWinTime`.
Added new class `EpochQuery` to represent the GRPC `EpochRequest`. Added the above calls to `ClientV2`
Changed documentation of unreleased `GetBakersRewardPeriod` and `GetBlockCertificates` to be consistent with the methods added here.
> Support new endpoints

- CHANGELOG.md
- concordium-sdk/src/main/java/com/concordium/sdk/ClientV2MapperExtensions.java
- concordium-sdk/src/main/java/com/concordium/sdk/responses/accountinfo/AccountDelegation.java
- concordium-sdk/src/main/java/com/concordium/sdk/responses/accountinfo/AccountInfo.java
- concordium-sdk/src/main/java/com/concordium/sdk/responses/accountinfo/Baker.java
- concordium-sdk/src/test/java/com/concordium/sdk/ClientV2GetAccountInfoTest.java
Fix https://github.com/Concordium/concordium-java-sdk/issues/306
- Fixed  parsing of the delegator / baker stake objects
- `Baker` and `AccountDelegation` now exposes `Optional<PendingChange>` as opposed to just
`PendingChange`.
- Fix `.equals` on `AccountInfo`
- Added a test
> Fix bug where AccountInfo could fail if there were no pendingchange for a delegator or validator.

- CHANGELOG.md
- concordium-sdk/src/main/java/com/concordium/sdk/responses/AccountIndex.java
Address https://github.com/Concordium/concordium-java-sdk/issues/308
Properly serialize the `AccountIndex` as 8 bytes as opposed to two bytes.
> Fix bug in AccountIndex serialization.

- CHANGELOG.md
- concordium-android-wallet-example/app/src/main/java/com/concordium/example/wallet/Storage.kt
- concordium-android-wallet-example/app/src/main/java/com/concordium/example/wallet/activities/AccountActivity.kt
- concordium-sdk/src/main/java/com/concordium/sdk/crypto/wallet/ConcordiumHdWallet.java
- concordium-sdk/src/test/java/com/concordium/sdk/crypto/wallet/ConcordiumHdWalletTest.java
Fix nonce issue in example wallet (breaking change from the SDK) and fix a bug in `ConcordiumHdWallet.fromSeedPhrase` where the generated seed was invalid (contained spaces).
- Use other nonce type.
- Remove spaces in seed as hex.
> Fix wallet sdk bugs

- concordium-sdk/src/main/java/com/concordium/sdk/crypto/wallet/Network.java
- concordium-sdk/src/main/java/com/concordium/sdk/crypto/wallet/identityobject/IdentityObject.java
- concordium-sdk/src/main/java/com/concordium/sdk/crypto/wallet/identityobject/MissingAttributeException.java
- concordium-sdk/src/main/java/com/concordium/sdk/crypto/wallet/web3Id/CredentialAttribute.java
- concordium-sdk/src/main/java/com/concordium/sdk/crypto/wallet/web3Id/Statement/AtomicStatement.java
- concordium-sdk/src/main/java/com/concordium/sdk/crypto/wallet/web3Id/Statement/MembershipStatement.java
- concordium-sdk/src/main/java/com/concordium/sdk/crypto/wallet/web3Id/Statement/NonMembershipStatement.java
- concordium-sdk/src/main/java/com/concordium/sdk/crypto/wallet/web3Id/Statement/RangeStatement.java
- concordium-sdk/src/main/java/com/concordium/sdk/crypto/wallet/web3Id/Statement/RequestStatement.java
- concordium-sdk/src/main/java/com/concordium/sdk/crypto/wallet/web3Id/Statement/RevealStatement.java
- concordium-sdk/src/main/java/com/concordium/sdk/crypto/wallet/web3Id/Statement/StatementType.java
- concordium-sdk/src/main/java/com/concordium/sdk/crypto/wallet/web3Id/Statement/did/AccountRequestIdentifier.java
- concordium-sdk/src/main/java/com/concordium/sdk/crypto/wallet/web3Id/Statement/did/RequestIdentifier.java
- concordium-sdk/src/main/java/com/concordium/sdk/crypto/wallet/web3Id/Statement/did/Web3IssuerRequestIdentifier.java
- concordium-sdk/src/main/java/com/concordium/sdk/responses/accountinfo/credential/AttributeType.java
- concordium-sdk/src/test/java/com/concordium/sdk/crypto/wallet/CredentialTest.java
- concordium-sdk/src/test/java/com/concordium/sdk/crypto/wallet/FileHelpers.java
- concordium-sdk/src/test/java/com/concordium/sdk/crypto/wallet/IdentityTest.java
- concordium-sdk/src/test/java/com/concordium/sdk/crypto/wallet/web3Id/CredentialAttributeTest.java
- concordium-sdk/src/test/java/com/concordium/sdk/crypto/wallet/web3Id/ProofTest.java
- concordium-sdk/src/test/java/com/concordium/sdk/crypto/wallet/web3Id/RequestStatementTest.java
- concordium-sdk/src/test/testresources/wallet/web3Id/accountRequestUnder18.json
Help for IdProofs in mobile wallet.
Added `canBeProvedBy` and `getUnsatisfiedStatements` to `RequestStatement`.
> Add methods for checking an identity satisfies a statement

- CHANGELOG.md
- concordium-sdk/src/main/java/com/concordium/sdk/cis2/SerializationUtils.java
- concordium-sdk/src/main/java/com/concordium/sdk/cis2/events/CustomEvent.java
Fix #324 
Removed the unnecesary `tag` field in `CustomEvent`
> Removed `tag` field from CustomEvent

- CHANGELOG.md
- concordium-sdk/src/main/java/com/concordium/sdk/crypto/CryptoJniNative.java
- concordium-sdk/src/main/java/com/concordium/sdk/crypto/wallet/ErrorResult.java
- concordium-sdk/src/main/java/com/concordium/sdk/crypto/wallet/web3Id/AcceptableRequest.java
- concordium-sdk/src/main/java/com/concordium/sdk/crypto/wallet/web3Id/AttributeCheck.java
- concordium-sdk/src/test/java/com/concordium/sdk/crypto/wallet/web3Id/RequestStatementTest.java
- crypto-jni/Cargo.lock
- crypto-jni/src/lib.rs
Add bindings for acceptable request / statement from concordium-base wallet_library.
> Acceptable request

- CHANGELOG.md
- concordium-sdk-examples/src/main/java/com/concordium/sdk/examples/SignMessage.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/MessageSigningDigest.java
- concordium-sdk/src/test/java/com/concordium/sdk/transactions/MessageSigningDigestTest.java
Facilitate message signing (CIS-3, WalletConnect signing) by adding digest generator. For the actual signing, `TransactionSigner` can be used.
- Added `MessageSigningDigest` class to generate digests for message signing
> JAV-320 Facilitate message signing

- .github/workflows/build-test.yml
- .github/workflows/release.yml
- .gitignore
- CHANGELOG.md
- concordium-android-sdk/pom.xml
- concordium-sdk-examples/pom.xml
- concordium-sdk/pom.xml
- concordium-sdk/src/main/java/com/concordium/sdk/responses/accountinfo/credential/AttributeType.java
- crypto-jni/Cargo.lock
- pom.xml
Add support for company ID attributes
- Add new `AttributeType` entries
- Update `concordium-base` to `38cf687`
- Update the base version to `7.2.0-SNAPSHOT`
> JAV-323 Support company ID attributes

- CHANGELOG.md
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/EncryptedTransferTransaction.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/EncryptedTransferWithMemoTransaction.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/TransactionFactory.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/TransferToEncryptedTransaction.java
Deprecate encrypted transfers. They are deprecated and partially removed since protocol version 7.
- Add deprecation annotations and Javadoc notices to builders, factory methods and classes associated with encrypted transfers
> JAV-324 Deprecate encrypted transfers

- CHANGELOG.md
- README.md
- concordium-android-sdk/pom.xml
- concordium-sdk-examples/pom.xml
- concordium-sdk/pom.xml
- pom.xml
> Merge release 8.0.0

- CHANGELOG.md
- concordium-sdk-examples/src/main/java/com/concordium/sdk/examples/ConfigureBaking.java
- concordium-sdk/src/main/java/com/concordium/sdk/ClientV2MapperExtensions.java
- concordium-sdk/src/main/java/com/concordium/sdk/transactions/ConfigureBakerPayload.java
- concordium-sdk/src/test/java/com/concordium/sdk/ClientV2GetAccountInfoTest.java
- concordium-sdk/src/test/java/com/concordium/sdk/transactions/ConfigureBakerTransactionTest.java
Fix incorrect type and behavior in ConfigureBakerPayload
- Changed `openForDelegation` field in `ConfigureBakerPayload` from `boolean` to `OpenStatus`: what used to be `false` is now `OpenStatus.OPEN_FOR_ALL`, what used to be `true` is now `OpenStatus.CLOSED_FOR_NEW`, and it is now possible to set `OpenStatus.CLOSED_FOR_ALL` as well
- Added `suspended` to the configure baking example
> Fix configure baker open status

- CHANGELOG.md
- concordium-sdk/src/main/java/com/concordium/sdk/ClientV2.java
Add `getPassiveDelegationInfo` endpoint providing information about the passive delegators at the end of a given block
- Added the endpoint
> Add getPassiveDelegationInfo endpoint
