README.md
To remind the user to update submodules in the README. 
* One step has been added to the `Build and usage` section.
* Some of the code blocks are now parsed as XML instead of plaintext.
=> Update README. 

concordium-sdk/pom.xml, scripts/README.md, scripts/set_sdk_version.sh
Introducing an initial way of releasing the code.
A script for bumping the versions required.
A README explaining the release process.
=> Release setup

release/README.md, scripts/set_sdk_version.sh
Remove an obsolete release script
Removed an obsolete release script and expanded the release README a bit.
=> Removed obsolete script

concordium-sdk/pom.xml
Release 1.0.0
Updated the version to 1.0.0 from 0.0.1.
=> Release 1.0.0

concordium-sdk/pom.xml
Release 1.0.1
Release 1.0.1 
Fixes 
- Deserialization of MicroGTUPerEuro
=> Release 1.0.1

concordium-sdk/pom.xml
Snapshot the new version after release. 
=> 1.0.2-SNAPSHOT

concordium-sdk/pom.xml
Prepare for a new development cycle and release.
Snapshotted the version 
=> 1.1.1-SNAPSHOT

CHANGELOG.md, concordium-sdk/pom.xml
Release 1.2.0 
Added support for 
`getBlocksAtHeight`
=> Release 1.2.0

concordium-sdk/pom.xml
Snapshot 
Snapshotted the version. 
=> Snapshotted

concordium-sdk/pom.xml
Release 1.3.0 
- Support for deserializing transactions 
- Support for getBlockInfo
=> release 1.3.0

CHANGELOG.md, concordium-sdk/src/main/java/com/concordium/sdk/responses/accountinfo/AccountInfo.java, concordium-sdk/src/main/java/com/concordium/sdk/responses/accountinfo/ScheduledRelease.java, concordium-sdk/src/main/java/com/concordium/sdk/responses/transactionstatus/Status.java, concordium-sdk/src/main/java/com/concordium/sdk/transactions/BlockItem.java, concordium-sdk/src/main/java/com/concordium/sdk/types/Timestamp.java, concordium-sdk/src/test/java/com/concordium/sdk/types/TimestampTest.java
Fix a bug in the JSON parsing related to `AccountInfo` 
In particular `ScheduledRelease` and `accountAddress` was missing.
Fixed the bugs. 
=> Fix bug when parsing AccountInfo

concordium-sdk/pom.xml
Snapshotting the version
Edited the pom.xml
=> Snapshotted the version.

CHANGELOG.md, concordium-sdk/src/main/java/com/concordium/sdk/transactions/AccountTransaction.java, concordium-sdk/src/main/java/com/concordium/sdk/transactions/BlockItemType.java, concordium-sdk/src/main/java/com/concordium/sdk/transactions/TransactionHeader.java, concordium-sdk/src/main/java/com/concordium/sdk/transactions/TransactionType.java, concordium-sdk/src/main/java/com/concordium/sdk/transactions/Transfer.java, concordium-sdk/src/main/java/com/concordium/sdk/transactions/TransferWithMemo.java
Expose more types related to transactions in the API. 
Prefixed a bunch of classes with `public`.
=> Expose transaction

CHANGELOG.md, concordium-sdk/pom.xml
Release 1.5.0
Expose more `transaction` types in the API. 
=> Release 1.5.0

CHANGELOG.md, concordium-sdk/pom.xml
Release 1.6.1
Fix a timeout bug. See changelog for details. 
Fixed the bug in the `Client`.
Set version in `pom.xml`
=> Release 1.6.1

concordium-sdk/pom.xml
1.6.2-SNAPSHOT
Edited the `pom.xml`
=> Snapshotted the version

CHANGELOG.md, concordium-sdk/pom.xml
Prepare release 2.0.0
- Support for TLS
Edited the `pom.xml`
=> Release 2.0.0

CHANGELOG.md, concordium-sdk/pom.xml
Exposed more types related to `TransactionSummary`
Made `TransactionResultEvent` `AbstractAccount` public and added some convenience functions for handling these. 
=> Release 2.3.0

CHANGELOG.md, concordium-sdk/pom.xml
Release 2.4.0
Support for `getCryptographicParameters`
Updated the CHANGELOG.md and the `pom.xml`.
=> Release 2.4.0

concordium-sdk/pom.xml
Snapshot the version
Edited the `pom.xml`
=> 2.4.1-snapshot

concordium-sdk/pom.xml
Snapshot the version
Edited `pom.xml`
=> 3.0.1-snapshot

CHANGELOG.md, README.md, concordium-sdk/src/main/java/com/concordium/sdk/Client.java
Adds support for Node Uptime
Adds support for Node Uptime
=> Query : PeerUptime

CHANGELOG.md, README.md, concordium-sdk/src/main/java/com/concordium/sdk/Client.java
Adds support for query `PeerTotalSent`
Adds support for query `PeerTotalSent`
=> Query : PeerTotalSent

CHANGELOG.md, README.md, concordium-sdk/pom.xml, concordium-sdk/src/main/java/com/concordium/sdk/Client.java, concordium-sdk/src/main/java/com/concordium/sdk/responses/peerList/Peer.java, concordium-sdk/src/main/java/com/concordium/sdk/responses/peerList/PeerCatchupStatus.java, concordium-sdk/src/main/java/com/concordium/sdk/responses/peerlist/PeerCatchupStatus.java
Adds support for query `PeerList`
Adds support for query `PeerList`
=> Query : PeerList

CHANGELOG.md, README.md, concordium-sdk/src/main/java/com/concordium/sdk/Client.java, concordium-sdk/src/main/java/com/concordium/sdk/responses/peerStats/PeerStat.java, concordium-sdk/src/main/java/com/concordium/sdk/responses/peerStats/PeerStatistics.java
Adds support for query `PeerStats`
Adds support for query `PeerStats`
=> Query : PeerStats

CHANGELOG.md, README.md, concordium-sdk/pom.xml, concordium-sdk/src/main/java/com/concordium/sdk/Client.java
Adds support for `PeerVersion`
Adds support for `PeerVersion`
=> Query : PeerVersion

CHANGELOG.md, README.md, concordium-sdk/src/main/java/com/concordium/sdk/Client.java
- Added support for query `JoinNetwork`
- Added support for query `LeaveNetwork`
- Added support for query `JoinNetwork`
- Added support for query `LeaveNetwork`
=> Query : Join & Leave network

CHANGELOG.md, README.md, concordium-sdk/src/main/java/com/concordium/sdk/Client.java
- Added support for query `PeerTotalReceived`
- Added support for query `PeerTotalReceived`
=> Query : Total Received

CHANGELOG.md, concordium-sdk/pom.xml
See CHANGELOG.md
This PR only bumps the version and updates the CHANGELOG.
=> Release 3.1.0

.github/workflows/build-test.yml, .gitmodules, concordium-sdk/pom.xml, crypto-jni/Cargo.lock, crypto-jni/Cargo.toml, crypto-jni/src/lib.rs
Point to grpc-api submodule in concordium-base instead of having a copy of a direct submodule.
=> Remove grpc-api as a direct submodule and use the one from base instead.

CHANGELOG.md, concordium-sdk/pom.xml
Release 4.1.0 
Support for new transactions. See the CHANGELOG for details.  https://github.com/Concordium/concordium-java-sdk/blob/main/CHANGELOG.md
Bump version and update CHANGELOG.
=> Release 4.1.0

concordium-sdk/pom.xml, concordium-sdk/src/main/java/com/concordium/sdk/ClientV2.java, concordium-sdk/src/main/java/com/concordium/sdk/ClientV2MapperExtensions.java, concordium-sdk/src/test/java/com/concordium/sdk/ClientV2GetAnonymityRevokersTest.java
Adds test infra for Client V2
Adds test for GetAnonymityRevokers
Adds test infra for Client V2
Adds test for GetAnonymityRevokers
=> GRPC V2 : GetAnonymityRevokerTest

CHANGELOG.md, concordium-sdk-examples/src/main/java/com/concordium/sdk/examples/GetAccountList.java, concordium-sdk/src/main/java/com/concordium/sdk/ClientV2.java, concordium-sdk/src/test/java/com/concordium/sdk/ClientV2GetAccountListTest.java
Adds support for GRPC V2 : Get Account List
Adds support for GRPC V2 : Get Account List
=> GRPC V2 : Get Account List 

CHANGELOG.md, concordium-sdk-examples/pom.xml, concordium-sdk-examples/src/main/java/com/concordium/sdk/examples/GetConsensusStatus.java, concordium-sdk/src/main/java/com/concordium/sdk/ClientV2.java, concordium-sdk/src/main/java/com/concordium/sdk/ClientV2MapperExtensions.java, concordium-sdk/src/main/java/com/concordium/sdk/responses/consensusstatus/ConsensusStatus.java, concordium-sdk/src/test/java/com/concordium/sdk/ClientV2GetConsensusStatusTest.java
Added support for GRPC V2 getConsensusInfo
Added support for GRPC V2 getConsensusInfo
=> GRPC-V2 : Get Consensus Status

CHANGELOG.md, concordium-sdk-examples/src/main/java/com/concordium/sdk/examples/GetPoolDelegators.java, concordium-sdk/src/main/java/com/concordium/sdk/ClientV2.java, concordium-sdk/src/test/java/com/concordium/sdk/ClientV2GetPoolDelegatorsTest.java
Added support for GRPC V2 : Get Pool Delegators
Added support for GRPC V2 : Get Pool Delegators
=> GRPC V2 : Get Pool Delegators

CHANGELOG.md, concordium-sdk-examples/src/main/java/com/concordium/sdk/examples/GetPassiveDelegators.java, concordium-sdk-examples/src/main/java/com/concordium/sdk/examples/GetPoolDelegators.java, concordium-sdk/src/main/java/com/concordium/sdk/ClientV2.java, concordium-sdk/src/main/java/com/concordium/sdk/ClientV2MapperExtensions.java, concordium-sdk/src/main/java/com/concordium/sdk/responses/DelegatorInfo.java, concordium-sdk/src/test/java/com/concordium/sdk/ClientV2GetPassiveDelegatorsTest.java, concordium-sdk/src/test/java/com/concordium/sdk/ClientV2GetPoolDelegatorsTest.java
Added support for GRPC V2 : Get Passive Delegators
Added support for GRPC V2 : Get Passive Delegators
=> GRPC V2 : Get Passive Delegators

CHANGELOG.md, concordium-sdk/pom.xml
Release 5.0.0
See changelog.
But this release brings support for the GRPCV2 API exposed by the node (and enabled by default)
=> Release 5.0.0

CHANGELOG.md, concordium-sdk-examples/pom.xml, concordium-sdk/pom.xml
_Describe the purpose of the pull request, link to issue describing the problem, etc.
=> Release 5.0.1

concordium-sdk-examples/pom.xml, concordium-sdk/pom.xml
_Describe the purpose of the pull request, link to issue describing the problem, etc.
=> snapshot the version.

CHANGELOG.md, concordium-sdk-examples/pom.xml, concordium-sdk/pom.xml, concordium-sdk/src/main/java/com/concordium/sdk/ClientV2.java
Remove an import which could lead to compilation error on some jdks.
=> Remove unused import.

concordium-sdk-examples/pom.xml, concordium-sdk/pom.xml
=> snapshot version.

concordium-sdk-examples/pom.xml, concordium-sdk/pom.xml
_Describe the purpose of the pull request, link to issue describing the problem, etc.
_Remove if not applicable.
=> snapshot version

CHANGELOG.md, concordium-sdk-examples/pom.xml, concordium-sdk/pom.xml
=> Release 6.0.0

concordium-sdk-examples/pom.xml, concordium-sdk/pom.xml
=> SNAPSHOT 6.0.1

CHANGELOG.md, concordium-sdk/src/main/java/com/concordium/sdk/responses/peerlist/PeerCatchupStatus.java, concordium-sdk/src/main/java/com/concordium/sdk/types/AccountAddress.java, concordium-sdk/src/main/java/com/concordium/sdk/types/ContractAddress.java, crypto-jni/Cargo.lock
Update `concordium-base` dependency and remove the remaining usages of GRPC V1 API.
=> Purge remaining usages V1 GRPC API.

CHANGELOG.md
=> Fix changelog for 6.1.0

CHANGELOG.md, concordium-android-sdk/pom.xml, concordium-sdk-examples/pom.xml, concordium-sdk/pom.xml, pom.xml
=> Bump to version 7.0.0

concordium-android-sdk/pom.xml, concordium-sdk-examples/pom.xml, concordium-sdk/pom.xml, pom.xml
=> bump to 7.0.1-SNAPSHOT

release/README.md
Update the release README to include details about the publishing to Maven central.
=> Update release README.md

concordium-android-sdk/pom.xml, concordium-sdk-examples/pom.xml, concordium-sdk/pom.xml, pom.xml
=> Bump to SNAPSHOT version

CHANGELOG.md, RELEASE.md, concordium-android-sdk/pom.xml, concordium-sdk-examples/pom.xml, concordium-sdk/pom.xml, concordium-sdk/src/main/java/com/concordium/sdk/transactions/Payload.java, concordium-sdk/src/main/java/com/concordium/sdk/transactions/TransactionTypeCost.java, pom.xml
Fix ConfigureDelegation transaction cost issues
- Exposed `Payload.calculateEnergyCost` method
- Fixed base cost of `ConfigureDelegation` transaction being bigger than needed
=> Fix transaction cost issues
